language: rust
rust:
  - nightly
  - beta
  - 1.4.0
  - 1.5.0
  - 1.6.0
  - 1.7.0
  - 1.8.0
before_script:
- |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH
script:
  - |
      cargo test &&
      travis-cargo --only nightly test -- --no-default-features
